### ISSUE TITLE
Exposed Username and password in URI

### ISSUE THREAD

**Issue by eth0izzle** [zeke13210/blackrock_backend#6]
**Potential security breach**. Verified credentials in URL `*redacted*:*redacted*@blackrocktaskmanager.c0uikdugnayd.us-east-1.rds.amazonaws.com` in file [/config.py](https://github.com/zeke13210/blackrock_backend/blob/master/config.py)<br/><br/>You should recycle your credentials immediately and move secrets to environment variables to prevent them being committed to GitHub.

**Comment by zeke13210** [comment]
removed config file from repo. Thanks!
